package com.example.meetuteam2.entities.enums;

public enum CityEnum {
    AOSTA("Aosta"),
    TORINO("Torino"),
    GENOVA("Genova"),
    MILANO("Milano"),
    TRENTO("Trento"),
    VENEZIA("Venezia"),
    TRIESTE("Trieste"),
    BOLOGNA("Bologna"),
    FIRENZE("Firenze"),
    ANCONA("Ancona"),
    PERUGIA("Perugia"),
    ROMA("Roma"),
    PESCARA("Pescara"),
    CAMPOBASSO("Campobasso"),
    NAPOLI("Napoli"),
    BARI("Bari"),
    POTENZA("Potenza"),
    CATANZARO("Catanzaro"),
    PALERMO("Palermo"),
    CAGLIARI("Cagliari"),

    WIEN("Wien"),
    MINSK("Minsk"),
    BRUXELLES("Bruxelles"),
    SARAJEVO("Sarajevo"),
    SOFIYA("Sofiya"),
    ZAGREB("Zagreb"),
    PRISHTINA("Prishtina"),
    PRAHA("Praha"),
    KØBENHAVN("Kobenhavn"),
    TALLINN("Tallinn"),
    HELSINKI("Helsinki"),
    PARIS("Paris"),
    BERLIN("Berlin"),
    ATHINA("Athina"),
    BUDAPEST("Budapest"),
    REYKJAVIK("Reykjavik"),
    DUBLIN("Dublin"),
    RIGA("Riga"),
    VADUZ("Vaduz"),
    VILNIUS("Vilinius"),
    LUXEMBOURG("Luxembourg"),
    SKOPJE("Skopje"),
    LA_VALLETTA("La Valletta"),
    CHISINAU("Chișinău"),
    MONACO_VILLE("Monaca-Ville"),
    PODGORICA("Podgorica"),
    AMSTERDAM("Amsterdam"),
    OSLO("Oslo"),
    WARSZAWA("Warszaw"),
    LISBOA("Lisboa"),
    BUCURESTI("București"),
    MOCKVA("Moskva"),
    CITTA_DI_SAN_MARINO("Città di San Marino"),
    BEOGRAD("Beograd"),
    BRATISLAVA("Bratislava"),
    LJUBLJANA("Ljubljana"),
    MADRID("Madrid"),
    STOCKHOLM("Stockholm"),
    BERN("Bern"),
    KYIV("Kyiv"),
    LONDON("London"),
    CITTA_DEL_VATICANO("Città del Vaticano"),

    TIRANE("Tirane"),
    ALGERIS("Algeris"),
    BUENOS_AIRES("Buenos Aires"),
    YEREVAN("Yerevan"),
    CANBERRA("Canberra"),
    BAKU("Baku"),
    DHAKA("Dhaka"),
    SUCRE("Sucre"),
    BRASILIA("Brasilia"),
    OTTAWA("Ottawa"),
    SANTIAGO("Santiago"),
    BEIJING("Beijing"),
    BOGOTA("Bogota"),
    SAN_JOSE("San José"),
    LA_HABANA("La Habana"),
    SANTO_DOMINGO("Santo Domingo"),
    QUITO("Quito"),
    AL_QAHIRAH("Al-Quahirah"),
    SAN_SALVADOR("San Salvador"),
    ADDIS_ABABA("Addis Ababa"),
    ACCRA("Accra"),
    CIUDAD_DE_GUATEMALA("Ciudad de Guatemala"),
    NEW_DELHI("New Delhi"),
    TEGUCIGALPA("Tegucigalpa"),
    JAKARTA("Jakarta"),
    TEHRAN("Tehran"),
    BAGHDAD("Baghdad"),
    JERUSALEM("Jerusalem"),
    KINGSTON("Kingston"),
    TOKYO("Tokyo"),
    AMMAN("Amman"),
    NUR_SULTAN("Nur-Sultan"),
    NAIROBI("Nairobi"),
    AL_KUWAYT("Al-Kuwayt"),
    BEIRUT("Beirut"),
    TRIPOLI("Tripoli"),
    ANTANANARIVO("Antananarivo"),
    KUALA_LUMPUR("Kuala Lampur"),
    PORT_LOUIS("Port Louis"),
    CIUDAD_DE_MEXICO("Ciudad de Mexico"),
    RABAT("Rabat"),
    MAPUTO("Maputo"),
    KATHMANDU("Kathmandu"),
    WELLINGTON("Wellington"),
    MANAGUA("Managua"),
    ABUJA("Abuja"),
    MUSCAT("Muscat"),
    ISLAMABAD("Islamabad"),
    CIUDAD_DE_PAN("Ciudad de pan"),
    CARACAS("Caracas");

    private String description;

    CityEnum(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
