spring:
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/meetu
    username: team2
    password: team2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
#local directory for storage
fileDirectory: C:\Meetu@FileStorage
#key for firebase storage
fireBaseKey: C:\file-storage-meetuat.json
